version: '3.8'
services:
  back:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test1234321
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "12345678"

    ports:
      - "15672:15672"
      - "5672:5672"
